---
  - name: install httpd
    yum: 
      name: httpd
      state: present
  - name: install java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: show java version
    command: java -version 
